[workspace]
resolver = "3"
members = [
    "actix_hello_world",
    "algoritmos/alg_guloso",
    "algoritmos/busca_binaria",
    "algoritmos/dijkstra",
    "algoritmos/oredenacao_por_selecao",
    "algoritmos/pesquisa_em_largura",
    "algoritmos/quicksort",
    "arc_mutex/arc",
    "arc_mutex/cache",
    "arc_mutex/canais",
    "arc_mutex/mutex",
    "arc_mutex/workers",
    "array",
    "branches",
    "cap1/hello_cargo",
    "cap10/10-1/maior-generic",
    "cap10/maior",
    "cap2/guessing_game",
    "cap3/funcao",
    "cap3/variables",
    "cap4/clone",
    "cap4/fixing-ownership",
    "cap4/mut-ref",
    "cap4/ownership",
    "cap4/reference-non-owning-pointers",
    "cap4/review_owner",
    "cap4/slice",
    "cap4/slice-type",
    "cap5/rectangle",
    "cap5/rectangle-struct",
    "cap5/rectangle-struct2",
    "cap5/rectangle-tuple",
    "cap5/retangulo",
    "cap6/cap6-1",
    "cap6/cap6-2/moeda",
    "cap6/cap6-3/iflet",
    "cap7/cap7-1/communicator",
    "cap7/cap7-2/try_me",
    "cap8/cap8-1/vec",
    "cap9/9-1/panic",
    "cap9/9-2/result",
    "cap9/9-3/palpite",
    "closures",
    "concorrencia",
    "dio/ActixWeb/actix-web-json-completo",
    "dio/ActixWeb/actix-web-simples",
    "dio/app_clientes_console",
    "dio/arc_mutex",
    "dio/asyncs",
    "dio/closure",
    "dio/custom_errors",
    "dio/desafio1-1",
    "dio/desafio1-2",
    "dio/desafio2-1",
    "dio/desafio2-2",
    "dio/desafio3-1",
    "dio/desafio3-2",
    "dio/enums",
    "dio/erro",
    "dio/generics",
    "dio/hashmap",
    "dio/idade",
    "dio/json",
    "dio/macro_file",
    "dio/matchex",
    "dio/mysql",
    "dio/orm_disel",
    "dio/orm_generics/model_macro",
    "dio/referencias",
    "dio/rocket/rocket-html-completo_aula",
    "dio/rocket/rocket-json-completo_aula",
    "dio/strings",
    "dio/structs",
    "dio/tabuada",
    "dio/testes/01 - unitario",
    "dio/testes/03 - comportamento",
    "dio/threads",
    "dio/traits",
    "dio/treinamento_rust",
    "enum_example",
    "envs",
    "error_handling",
    "function",
    "iterators",
    "loops",
    "match_example",
    "minigrep",
    "mods",
    "nao_tem_null",
    "rand",
    "read_file",
    "rocket_hello_world",
    "rustfs/backend",
    "rustfs/frontend",
    "somador",
    "testes",
    "text_to_emoji",
    "tipos",
    "uppercaser",
    "variaveis",
]
